CREATE table "MEMBER" (
"ID" VARCHAR2(30) NOT NULL,
"PASSWD" VARCHAR2(30) NOT NULL,
"NAME" VARCHAR2(50) NOT NULL,
"MAIL" VARCHAR2(50) NOT NULL,
constraint "MEMBER_PK" primary key ("ID")
);
CREATE TABLE "PRODUCT" 
( "NAME" VARCHAR2(100) NOT NULL ENABLE, 
"PRICE" NUMBER(10,0) NOT NULL ENABLE, 
"COUNT" NUMBER(10,0) NOT NULL ENABLE, 
"CATEGORY" VARCHAR2(100) NOT NULL ENABLE, 
"TYPE" VARCHAR2(100) NOT NULL ENABLE, 
"PHOTO_DETAIL" VARCHAR2(1000) NOT NULL ENABLE, 
"PHOTO_PREVIEW" VARCHAR2(1000) NOT NULL ENABLE, 
"ORIGIN" VARCHAR2(100) NOT NULL ENABLE, 
"BRAND" VARCHAR2(1000) NOT NULL ENABLE, 
"NO" NUMBER(8,0), 
CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("NO") ENABLE
) ;

CREATE TABLE "PURCHASE" 
( "ID" VARCHAR2(30) NOT NULL ENABLE, 
"ITEM" VARCHAR2(100) NOT NULL ENABLE, 
"AMOUNT" NUMBER(10,0) NOT NULL ENABLE, 
"ADDR" VARCHAR2(4000) NOT NULL ENABLE, 
"PHONE" VARCHAR2(1000), 
CONSTRAINT "PURCHASE_PK" PRIMARY KEY ("ID") ENABLE
);
CREATE table "BUYLIST" (
"PHOTO" VARCHAR2(1000) NOT NULL,
"NAME" VARCHAR2(100) NOT NULL,
"COUNT" NUMBER(10,0) NOT NULL,
"PRICE" NUMBER(10,0) NOT NULL,
"CUSTOMER" VARCHAR2(30) NOT NULL
)
INSERT INTO MEMBER VALUES('admin', 'admin', '°ü¸®ÀÚ', 'admin@scsa.com');
commit;